# Pregunta 1

In [2]:
import numpy as np

In [3]:
arr_1 = np.array([1, 2, 3, 4])
arr_2 = arr_1[:3]
arr_2[0] = 10
list_1 = [1, 2, 3, 4]
list_2 = list_1[:3]
list_2[0] = 10
print(list_1, arr_1)

[1, 2, 3, 4] [10  2  3  4]


# Pregunta 2

In [4]:
arr_1 = np.array([10,  2,  8,  7,  6,  5])
print(np.argsort(arr_1))

[1 5 4 3 2 0]


# Pregunta 3

In [5]:
arr_1 = np.array([10,  2,  8,  7,  6,  5,  4,  1,  9,  3])
list_1 = [0, 3, 5, -2]
print(arr_1[list_1])

[10  7  5  9]


# Pregunta 4

In [6]:
arr_1 = np.array([10,  2,  8,  7,  6,  5,  4,  1,  9,  3])
arr_sorted_1 = arr_1.sort()
arr_sorted_2 = np.sort(arr_1)
print(arr_1, arr_sorted_1, arr_sorted_2)

[ 1  2  3  4  5  6  7  8  9 10] None [ 1  2  3  4  5  6  7  8  9 10]
